export default {
  login: 'yknx4',
  id: 1848186,
  node_id: 'MDQ6VXNlcjE4NDgxODY=',
  avatar_url: 'https://avatars.githubusercontent.com/u/1848186?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/yknx4',
  html_url: 'https://github.com/yknx4',
  followers_url: 'https://api.github.com/users/yknx4/followers',
  following_url: 'https://api.github.com/users/yknx4/following{/other_user}',
  gists_url: 'https://api.github.com/users/yknx4/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/yknx4/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/yknx4/subscriptions',
  organizations_url: 'https://api.github.com/users/yknx4/orgs',
  repos_url: 'https://api.github.com/users/yknx4/repos',
  events_url: 'https://api.github.com/users/yknx4/events{/privacy}',
  received_events_url: 'https://api.github.com/users/yknx4/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ale Ornelas Figueroa',
  company: '@HeyHomie',
  blog: 'http://www.ale.world',
  location: 'Mexico',
  email: null,
  hireable: true,
  bio: 'Devops Leader at @HeyHomie\r\n\r\nFormer Devops Engineer at @gitamv',
  twitter_username: null,
  public_repos: 190,
  public_gists: 31,
  followers: 36,
  following: 9,
  created_at: '2012-06-13T21:56:55Z',
  updated_at: '2021-12-01T23:01:43Z'
}
